//! Minimal deterministic package-manifest and path-dependency support.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PackageManifest {
    pub root: PathBuf,
    pub name: String,
    pub version: String,
    pub dependencies: BTreeMap<String, PathBuf>,
}

impl PackageManifest {
    pub fn discover(source: &Path) -> Result<Option<Self>, String> {
        let mut directory = source.parent();
        while let Some(candidate) = directory {
            let manifest = candidate.join("forma.toml");
            if manifest.is_file() {
                return Self::load(&manifest).map(Some);
            }
            directory = candidate.parent();
        }
        Ok(None)
    }

    pub fn load(path: &Path) -> Result<Self, String> {
        let source = std::fs::read_to_string(path)
            .map_err(|error| format!("failed to read {}: {error}", path.display()))?;
        let root = path.parent().unwrap_or(Path::new(".")).to_path_buf();
        let mut section = String::new();
        let mut name = None;
        let mut version = None;
        let mut dependencies = BTreeMap::new();

        for (line_index, raw_line) in source.lines().enumerate() {
            let line = raw_line.split('#').next().unwrap_or("").trim();
            if line.is_empty() {
                continue;
            }
            if line.starts_with('[') && line.ends_with(']') {
                section = line[1..line.len() - 1].to_string();
                continue;
            }
            let Some((key, value)) = line.split_once('=') else {
                return Err(format!(
                    "{}:{}: expected `key = value`",
                    path.display(),
                    line_index + 1
                ));
            };
            let key = key.trim();
            let value = value.trim();
            match section.as_str() {
                "package" if key == "name" => name = Some(parse_string(value, path, line_index)?),
                "package" if key == "version" => {
                    version = Some(parse_string(value, path, line_index)?)
                }
                "deps" | "dependencies" => {
                    let dependency = parse_path_dependency(value, path, line_index)?;
                    dependencies.insert(key.to_string(), dependency);
                }
                _ => {}
            }
        }

        Ok(Self {
            root,
            name: name.ok_or_else(|| format!("{}: missing package.name", path.display()))?,
            version: version
                .ok_or_else(|| format!("{}: missing package.version", path.display()))?,
            dependencies,
        })
    }

    /// Stable lockfile representation. Path dependencies are canonicalized when
    /// available and sorted by dependency name through `BTreeMap`.
    pub fn lockfile(&self) -> String {
        let mut output = format!(
            "# Generated by Forma; do not edit.\nversion = 1\n\n[[package]]\nname = \"{}\"\nversion = \"{}\"\n",
            self.name, self.version
        );
        for (name, path) in &self.dependencies {
            output.push_str(&format!(
                "\n[[dependency]]\nname = \"{name}\"\nsource = \"path+{}\"\n",
                path.to_string_lossy().replace('\\', "\\\\")
            ));
        }
        output
    }

    pub fn write_lockfile(&self) -> Result<PathBuf, String> {
        let path = self.root.join("forma.lock");
        let contents = self.lockfile();
        if std::fs::read_to_string(&path).ok().as_deref() != Some(contents.as_str()) {
            std::fs::write(&path, contents)
                .map_err(|error| format!("failed to write {}: {error}", path.display()))?;
        }
        Ok(path)
    }
}

fn parse_string(value: &str, path: &Path, line_index: usize) -> Result<String, String> {
    value
        .strip_prefix('"')
        .and_then(|value| value.strip_suffix('"'))
        .map(str::to_owned)
        .ok_or_else(|| {
            format!(
                "{}:{}: expected a quoted string",
                path.display(),
                line_index + 1
            )
        })
}

fn parse_path_dependency(value: &str, path: &Path, line_index: usize) -> Result<PathBuf, String> {
    let body = value
        .strip_prefix('{')
        .and_then(|value| value.strip_suffix('}'))
        .ok_or_else(|| {
            format!(
                "{}:{}: only path dependencies are currently supported",
                path.display(),
                line_index + 1
            )
        })?;
    for field in body.split(',') {
        let Some((name, value)) = field.split_once('=') else {
            continue;
        };
        if name.trim() == "path" {
            return parse_string(value.trim(), path, line_index).map(PathBuf::from);
        }
    }
    Err(format!(
        "{}:{}: path dependency requires `path = \"...\"`",
        path.display(),
        line_index + 1
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn manifest_and_lockfile_are_deterministic() {
        let directory = tempfile::tempdir().unwrap();
        let manifest = directory.path().join("forma.toml");
        std::fs::write(
            &manifest,
            "[package]\nname = \"app\"\nversion = \"0.1.0\"\n\n[deps]\nz = { path = \"../z\" }\na = { path = \"../a\" }\n",
        )
        .unwrap();
        let manifest = PackageManifest::load(&manifest).unwrap();
        let lock = manifest.lockfile();
        assert!(lock.find("name = \"a\"").unwrap() < lock.find("name = \"z\"").unwrap());
        assert_eq!(lock, manifest.lockfile());
    }
}
